version: '3.1'

services:

  postgres:
    container_name: postgres_store_go
    image: postgres
    environment:
      POSTGRES_PASSWORD: Test123*
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data